/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NbBadge: typeof import('@nubisco/ui/components/Badge')['NbBadge']
    NbBanner: typeof import('@nubisco/ui/components/Banner')['NbBanner']
    NbBarChart: typeof import('@nubisco/ui/components/Charts/BarChart')['NbBarChart']
    NbBreadcrumbs: typeof import('@nubisco/ui/components/Breadcrumbs')['NbBreadcrumbs']
    NbButton: typeof import('@nubisco/ui/components/Button')['NbButton']
    NbDataTable: typeof import('@nubisco/ui/components/DataTable')['NbDataTable']
    NbField: typeof import('@nubisco/ui/components/Field')['NbField']
    NbGrid: typeof import('@nubisco/ui/components/Grid')['NbGrid']
    NbIcon: typeof import('@nubisco/ui/components/Icon')['NbIcon']
    NbInterpolationChart: typeof import('@nubisco/ui/components/Charts/InterpolationChart')['NbInterpolationChart']
    NbLineChart: typeof import('@nubisco/ui/components/Charts/LineChart')['NbLineChart']
    NbMessage: typeof import('@nubisco/ui/components/Message')['NbMessage']
    NbNumberInput: typeof import('@nubisco/ui/components/NumberInput')['NbNumberInput']
    NbPanel: typeof import('@nubisco/ui/components/Panel')['NbPanel']
    NbProgressBar: typeof import('@nubisco/ui/components/ProgressBar')['NbProgressBar']
    NbRadio: typeof import('@nubisco/ui/components/Radio')['NbRadio']
    NbSelect: typeof import('@nubisco/ui/components/Select')['NbSelect']
    NbShell: typeof import('@nubisco/ui/components/Shell')['NbShell']
    NbShellPanel: typeof import('@nubisco/ui/components/ShellPanel')['NbShellPanel']
    NbSidebarLink: typeof import('@nubisco/ui/components/SidebarLink')['NbSidebarLink']
    NbSparkline: typeof import('@nubisco/ui/components/Charts/Sparkline')['NbSparkline']
    NbSwitch: typeof import('@nubisco/ui/components/Switch')['NbSwitch']
    NbTabs: typeof import('@nubisco/ui/components/Tabs')['NbTabs']
    NbTextInput: typeof import('@nubisco/ui/components/TextInput')['NbTextInput']
    NbUserMenu: typeof import('@nubisco/ui/components/UserMenu')['NbUserMenu']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
